# Generated by Django 5.2.17 on 2026-08-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("fiscal_year", models.IntegerField()),
                ("payload", models.JSONField()),
                (
                    "proposed_by",
                    models.CharField(default="extraction-flywheel", max_length=100),
                ),
                (
                    "citation_check",
                    models.TextField(
                        blank=True,
                        help_text="Independent citation-check summary produced by an agent that sees only the proposal and its source, never the extractor's reasoning.",
                    ),
                ),
                (
                    "synthetic",
                    models.BooleanField(
                        default=False,
                        help_text="True for demonstration cases that model a failure mode; never mixed with real filings undeclared.",
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("source_note", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("gated", "Gated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "gate_status",
                    models.CharField(
                        blank=True,
                        help_text="Verdict from the .NET gate: publishable, or a named failure mode.",
                        max_length=40,
                    ),
                ),
                ("gate_detail", models.TextField(blank=True)),
                ("gate_delta_pct", models.FloatField(blank=True, null=True)),
                (
                    "gate_segment_sum_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("gate_checked_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=150)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["company", "-fiscal_year"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "fiscal_year"),
                        name="one_proposal_per_company_year",
                    )
                ],
            },
        ),
    ]
