# Generated by Django 5.2.17 on 2026-08-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adjudication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EdgeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("gated", "Gated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gate_status", models.CharField(blank=True, max_length=60)),
                ("gate_detail", models.TextField(blank=True)),
                ("gate_checked_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=150)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kg_draft_id", models.IntegerField(unique=True)),
                ("edge_kind", models.CharField(default="supplies", max_length=30)),
                ("supplier_id", models.CharField(max_length=64)),
                ("supplier_name", models.CharField(blank=True, max_length=300)),
                ("customer_id", models.CharField(max_length=64)),
                ("customer_name", models.CharField(blank=True, max_length=300)),
                ("component_desc", models.TextField(blank=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("replaceability", models.IntegerField(blank=True, null=True)),
                ("disclosed_value", models.FloatField(blank=True, null=True)),
                ("disclosed_currency", models.CharField(blank=True, max_length=8)),
                ("disclosed_basis", models.CharField(blank=True, max_length=60)),
                ("contract_value_usd", models.FloatField(blank=True, null=True)),
                ("rationale", models.TextField(blank=True)),
                ("contributor", models.CharField(blank=True, max_length=100)),
                ("sources", models.JSONField(blank=True, null=True)),
                ("kg_status", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "ordering": ["kg_draft_id"],
            },
        ),
        migrations.CreateModel(
            name="KgRelationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("source_table", models.CharField(max_length=100)),
                ("live_count", models.IntegerField()),
                ("ref_cols", models.JSONField(default=list)),
                ("captured_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-live_count"],
            },
        ),
        migrations.CreateModel(
            name="MergeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("gated", "Gated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gate_status", models.CharField(blank=True, max_length=60)),
                ("gate_detail", models.TextField(blank=True)),
                ("gate_checked_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=150)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("survivor_id", models.CharField(blank=True, max_length=64)),
                ("survivor_name", models.CharField(max_length=300)),
                ("loser_id", models.CharField(blank=True, max_length=64)),
                ("loser_name", models.CharField(max_length=300)),
                (
                    "shared_identity",
                    models.BooleanField(
                        default=False,
                        help_text="Same LEI or intel_id resolved on both nodes.",
                    ),
                ),
                ("survivor_substance", models.JSONField(blank=True, default=dict)),
                ("loser_substance", models.JSONField(blank=True, default=dict)),
                ("note", models.TextField(blank=True)),
                (
                    "demo",
                    models.BooleanField(
                        default=False, help_text="Seeded demonstration case."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TypeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("gated", "Gated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gate_status", models.CharField(blank=True, max_length=60)),
                ("gate_detail", models.TextField(blank=True)),
                ("gate_checked_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=150)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kg_item_id", models.IntegerField(unique=True)),
                ("ref_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=300)),
                ("current_type", models.CharField(blank=True, max_length=60)),
                ("proposed_type", models.CharField(blank=True, max_length=60)),
                ("reason", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=60)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("kg_status", models.CharField(blank=True, max_length=30)),
                ("substance", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["kg_item_id"],
            },
        ),
        migrations.CreateModel(
            name="KgNodeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("source_table", models.CharField(max_length=100)),
                ("live_count", models.IntegerField()),
                ("captured_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-live_count"],
                "unique_together": {("name", "source_table")},
            },
        ),
    ]
